services:
  backend:
    build: 
      context: ./
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DATABASE_URL: postgresql://postgres:sujal@db:5432/taskapp
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: postgres:17.6
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sujal
      POSTGRES_DB: taskapp
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 